#set UnusedPin
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullnone [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_bl]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_hs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_vs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_de]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_pclk]
set_property PACKAGE_PIN T5 [get_ports lcd_de]
set_property PACKAGE_PIN U5 [get_ports lcd_bl]
set_property PACKAGE_PIN Y7 [get_ports lcd_hs]
set_property PACKAGE_PIN U8 [get_ports lcd_pclk]
set_property PACKAGE_PIN Y6 [get_ports lcd_vs]
set_property PACKAGE_PIN U10 [get_ports {lcd_data[15]}]
set_property PACKAGE_PIN W11 [get_ports {lcd_data[14]}]
set_property PACKAGE_PIN Y11 [get_ports {lcd_data[13]}]
set_property PACKAGE_PIN Y12 [get_ports {lcd_data[12]}]
set_property PACKAGE_PIN Y13 [get_ports {lcd_data[11]}]
set_property PACKAGE_PIN W8 [get_ports {lcd_data[10]}]
set_property PACKAGE_PIN U9 [get_ports {lcd_data[9]}]
set_property PACKAGE_PIN V10 [get_ports {lcd_data[8]}]
set_property PACKAGE_PIN V11 [get_ports {lcd_data[7]}]
set_property PACKAGE_PIN W9 [get_ports {lcd_data[6]}]
set_property PACKAGE_PIN W10 [get_ports {lcd_data[5]}]
set_property PACKAGE_PIN U7 [get_ports {lcd_data[4]}]
set_property PACKAGE_PIN V7 [get_ports {lcd_data[3]}]
set_property PACKAGE_PIN V8 [get_ports {lcd_data[2]}]
set_property PACKAGE_PIN Y8 [get_ports {lcd_data[1]}]
set_property PACKAGE_PIN Y9 [get_ports {lcd_data[0]}]


set_property PACKAGE_PIN N18 [get_ports tmds_clk_p_0]
set_property PACKAGE_PIN N20 [get_ports {tmds_data_p_0[2]}]
set_property PACKAGE_PIN T20 [get_ports {tmds_data_p_0[1]}]
set_property PACKAGE_PIN V20 [get_ports {tmds_data_p_0[0]}]
set_property IOSTANDARD TMDS_33 [get_ports tmds_clk_p_0]
set_property IOSTANDARD TMDS_33 [get_ports tmds_clk_n_0]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p_0[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_n_0[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p_0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_n_0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_p_0[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {tmds_data_n_0[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_txc]
set_property PACKAGE_PIN R19 [get_ports MDIO_PHY_0_mdio_io]
set_property PACKAGE_PIN H17 [get_ports RGMII_0_txc]
set_property PACKAGE_PIN H16 [get_ports RGMII_0_rxc]
set_property PACKAGE_PIN G18 [get_ports {RGMII_0_td[1]}]
set_property PACKAGE_PIN N16 [get_ports {RGMII_0_rd[3]}]
set_property PACKAGE_PIN M14 [get_ports {RGMII_0_rd[2]}]
set_property PACKAGE_PIN M15 [get_ports {RGMII_0_rd[0]}]
set_property PACKAGE_PIN M17 [get_ports {RGMII_0_rd[1]}]
set_property PACKAGE_PIN M18 [get_ports RGMII_0_rx_ctl]
set_property PACKAGE_PIN K16 [get_ports {RGMII_0_td[2]}]
set_property PACKAGE_PIN J16 [get_ports {RGMII_0_td[0]}]
set_property PACKAGE_PIN J15 [get_ports {RGMII_0_td[3]}]
set_property PACKAGE_PIN G14 [get_ports RGMII_0_tx_ctl]
set_property PACKAGE_PIN R17 [get_ports MDIO_PHY_0_mdc]





set_property PACKAGE_PIN T19 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN T10 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk5x]
set_property PACKAGE_PIN L15 [get_ports clk5x]

set_property PACKAGE_PIN N20 [get_ports {TMDS_0_data_p[2]}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_0_data_p[1]}]
set_property PACKAGE_PIN V20 [get_ports {TMDS_0_data_p[0]}]
set_property PACKAGE_PIN N18 [get_ports TMDS_0_clk_p]
